#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Fail-closed inventory of unresolved IA-64 translator fallback *sites*.

This is not an ISA-completeness oracle. A fallback site can represent many
legal encodings, reserved encodings, ignored encodings, or a combination.
The positive, assembler-backed F1-F16 oracle lives in ia64-isa-coverage.py.

Usage:
  python3 scripts/ia64-nonf-fallback-audit.py --check
  python3 scripts/ia64-nonf-fallback-audit.py --record
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
TRANSLATOR = Path("target/ia64/translate.c")
BASELINE = Path("tests/ia64/nonf/fallback-baseline.json5")
REPORT = Path("docs/generated/ia64-nonf-fallbacks.md")

# Only exact, reviewed source call labels are allowed. New labels must be
# investigated before being added; do not classify from arbitrary substrings.
LABEL_UNITS = {
    "A-slot": "A",
    "I-slot": "I",
    "mux1 mbtype": "I",
    "M-slot": "M",
    "M-slot op6/7": "M",
    "mov msr": "M",
    "B-slot": "B",
    "B-slot major=4 btype": "B",
    "X-slot": "LX",
    "X-slot op0": "LX",
    "F-slot": "F",
    "reserved template": "TEMPLATE",
    "bad slot": "OTHER",
    "dynamic:unimpl_msg": "BREAK_HELPER",
}
NON_F = ("A", "I", "M", "B", "LX")
# Match only complete statement lines; unlike grep this does not count the
# gen_unimpl declaration or documentation strings as fallback call sites.
CALL = re.compile(
    r'^\s*gen_unimpl\s*\(\s*ctx\s*,\s*insn\s*,\s*'
    r'(?P<arg>"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)'
    r'\s*\)\s*;\s*$',
    re.MULTILINE,
)


def scan(text: str) -> dict:
    lines = text.splitlines()
    ordinal: dict[str, int] = {}
    sites = []
    for match in CALL.finditer(text):
        arg = match.group("arg")
        label = arg[1:-1] if arg.startswith('"') else "dynamic:" + arg
        if label not in LABEL_UNITS:
            raise ValueError("unknown gen_unimpl call label: " + label)
        unit = LABEL_UNITS[label]
        ordinal[label] = ordinal.get(label, 0) + 1
        lineno = text.count("\n", 0, match.start()) + 1
        # Guard the actual production call and its immediate routing context.
        context = "\n".join(s.strip() for s in
                             lines[max(0, lineno - 5):min(len(lines), lineno + 1)])
        sites.append({
            "id": f"{label}#{ordinal[label]}",
            "unit": unit,
            "label": label,
            "line": lineno,
            "context_sha256": hashlib.sha256(context.encode()).hexdigest(),
            "classification": (
                "not-adjudicated" if unit in NON_F else "not-in-non-f-scope"
            ),
        })
    if not sites:
        raise ValueError("translator has no fallback observations")
    counts = {unit: sum(s["unit"] == unit for s in sites)
              for unit in (*NON_F, "F", "TEMPLATE", "BREAK_HELPER", "OTHER")}
    return {
        "schema_version": 1,
        "scope": "translator-source-fallback-sites-only",
        "isa_complete": False,
        "reference": {
            "title": "Intel Itanium Architecture Software Developer Manual",
            "volume": 3,
            "revision": "2.3",
            "document": "323207",
            "sections": ["4.2", "4.3", "4.4", "4.5", "4.7"],
        },
        "source": str(TRANSLATOR),
        "counts_by_unit": counts,
        "sites": sites,
    }


def render_markdown(snapshot: dict) -> str:
    counts = snapshot["counts_by_unit"]
    non_f_count = sum(counts[k] for k in NON_F)
    out = [
        "# IA-64 non-F translator fallback-site observations",
        "",
        "Generated by `scripts/ia64-nonf-fallback-audit.py --record`; "
        "do not edit by hand.",
        "",
        "**ISA COMPLETE: NO.** This is a *source call-site inventory*, "
        "not a count of missing instructions.",
        "",
        "Pinned normative reference: Intel Itanium Architecture Software "
        "Developer Manual, Volume 3, revision 2.3, document 323207; "
        "sections 4.2 (A), 4.3 (I), 4.4 (M), 4.5 (B), and 4.7 (X).",
        "",
        f"Observed non-F sites: **{non_f_count}**. "
        f"All observed call sites including F/other: **{len(snapshot['sites'])}**.",
        "",
        "| Unit | Translator fallback sites |",
        "|---|---:|",
    ]
    for unit, count in counts.items():
        out.append(f"| {unit} | {count} |")
    out.extend([
        "",
        "## Exact source fallbacks",
        "",
        "| Stable label | Unit | Current source line | Classification |",
        "|---|---|---:|---|",
    ])
    for site in snapshot["sites"]:
        out.append(
            f"| `{site['id']}` | {site['unit']} | {site['line']} | "
            f"{site['classification']} |"
        )
    out.extend([
        "",
        "## Required next audit (not yet done)",
        "",
        "For each instruction format, transcribe reference-backed opcode and "
        "extension-field assignments; expand operand/qualifying-predicate "
        "profiles; classify normal, ignored, unconditional-reserved, "
        "conditionally-reserved, and processor-generation-dependent cases. "
        "Compare each legal encoding against production translation, then "
        "add real execution and architectural exception tests.",
        "",
        "A generic fallback may be the **correct** implementation of a "
        "reserved encoding, or it may mask multiple legal instructions. "
        "An implemented path may be numerically or architecturally wrong. "
        "Do not treat source grep, fallback-site counts, or successful "
        "assembly as proof of ISA completeness.",
        "",
        "Dynamic `unimpl_msg` calls belong to the break/callgate helper "
        "and are tracked separately, rather than assigned to A/I/M/B/X.",
        "The F unit already has a separate positive-family audit; "
        "its remaining generic fallback is for non-positive/unadjudicated "
        "encodings, not evidence of a missing named family.",
        "",
        "## Reproduce",
        "",
        "```sh",
        "python3 scripts/ia64-nonf-fallback-audit.py --check",
        "python3 -m unittest discover -s tests/ia64/nonf -p 'test_*.py'",
        "# Only after reviewing intentional decoder changes:",
        "python3 scripts/ia64-nonf-fallback-audit.py --record",
        "```",
        "",
    ])
    return "\n".join(out)


def run(root: Path, mode: str) -> int:
    source = root / TRANSLATOR
    baseline = root / BASELINE
    report = root / REPORT
    snapshot = scan(source.read_text())
    expected_report = render_markdown(snapshot)
    if mode == "record":
        baseline.parent.mkdir(parents=True, exist_ok=True)
        report.parent.mkdir(parents=True, exist_ok=True)
        # Strict JSON is also valid JSON5; keep the .json5 project convention.
        baseline.write_text(json.dumps(snapshot, indent=2) + "\n")
        report.write_text(expected_report)
    else:
        if not baseline.exists() or not report.exists():
            raise ValueError("missing review-controlled baseline/report; use --record")
        recorded = json.loads(baseline.read_text())
        if recorded != snapshot:
            raise ValueError("fallback site inventory drift: review then --record")
        if report.read_text() != expected_report:
            raise ValueError("generated non-F report drift: review then --record")
    count = sum(snapshot["counts_by_unit"][k] for k in NON_F)
    print(f"NON-F FALLBACK {mode.upper()} PASS: {count} non-F call sites; "
          f"{len(snapshot['sites'])} total observed; ISA COMPLETE=NO")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--record", action="store_true")
    group.add_argument("--check", action="store_true")
    p.add_argument("--root", type=Path, default=ROOT)
    a = p.parse_args()
    try:
        return run(a.root.resolve(), "record" if a.record else "check")
    except (OSError, ValueError) as exc:
        print(f"non-F fallback audit: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
